# The plugin will choose one of the MOTD, randomly.
motd:
  enable: true
  list:
  - "&eAn MOTD"
  - "&aTwo\n&eLines"
  - "&cCannot do 3"
# The protocol is this: http://prntscr.com/suu98b
# The "Spigot 1.15.2" on the TOP right when you have older version
protocol:
  enable: true
  message: "&aWelcome there (%online%/%maxplayer%)"
  protocol_id: 1

# Edit value about players amount
players:
  # Virtual max player (Don't change the bungee config)
  max:
    enable: true
    amount: 400

  # Edit the amount of online players
  online:
    enable: false
    # A mathemathic expression to calculate the player amount
    # %online% will be replaced by the real amount of player.
    calculation: "%online% * 2"

# Text lines showed when you put your mouse hover the protocol, you see:
# http://prntscr.com/suu9rd
sample:
  enable: true
  list:
  - "&aWelcome here !"
  - " "
  - "&7&lSite"
  - "  &6my.site"
  - "  "
  - "&a» %online% joueurs connectés"
